ingress-nginx:
  controller:
    ingressClass: "tailscale-debug"

    updateStrategy:
      type: Recreate

    ingressClassResource:
      name: "tailscale-debug"

    publishService:
      enabled: true

    service:
      type: NodePort

    extraContainers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-token
              key: token
        - name: TS_KUBE_SECRET
          value: tailscale-state
        - name: TS_ACCEPT_DNS
          value: "false"
        - name: TS_USERSPACE
          value: "false"
          
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW

      - name: tailscale-ingress
        image: host.k3d.internal:15555/tailscale-ingress-controller:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: tic-debug-nic-controller

    extraVolumes:
      - name: token
        secret:
          secretName: tailscale-token