resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.localhost:15000/tailscale-lb-controller
  newTag: 87e0932
commonAnnotations:
  pthomison.com/image-repo: registry.localhost:15000/tailscale-lb-controller:87e0932
  pthomison.com/image-tag: 87e0932
