ingress-nginx:
  nameOverride: "nic"

  controller:
    ingressClass: "tailscale"

    ingressClassResource:
      name: "tailscale"

    publishService:
      enabled: true

    service:
      type: NodePort

    extraContainers:
      - name: tailscale-ingress-controller
        image: pthomison/tailscale-ingress-controller:26bc001
        volumeMounts:
        - name: token
          mountPath: "/opt/tailscale"
          readOnly: true
        - name: tailscale-storage
          mountPath: "/var/lib/tailscale/"

        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: "tailscale-ingress-controller-nic-controller"


    extraVolumes:
      - name: token
        secret:
          secretName: tailscale-token
      - name: tailscale-storage
        persistentVolumeClaim:
          claimName: tailscale-ingress-controller-storage