apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-rbac
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-nic
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-rbac
rules:
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - patch
  - update
  - get
  - create
