name: Build & Push Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: pthomison
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push - tailscale-lb-controller
      uses: docker/build-push-action@v4
      with:
        cache-from: type=registry,ref=pthomison/tailscale-lb-controller:buildcache
        cache-to: type=registry,ref=pthomison/tailscale-lb-controller:buildcache,mode=max
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pthomison/tailscale-lb-controller:${{env.tag}}
      
    - name: Build & Push - tailscale-lb
      uses: docker/build-push-action@v4
      with:
        cache-from: type=registry,ref=pthomison/tailscale-lb:buildcache
        cache-to: type=registry,ref=pthomison/tailscale-lb:buildcache,mode=max
        context: .
        file: tailscalelb.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pthomison/tailscale-lb:${{env.tag}}