name: Build & Push Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: pthomison
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        cache-from: type=registry,ref=pthomison/tailscale-ingress-controller:buildcache
        cache-to: type=registry,ref=pthomison/tailscale-ingress-controller:buildcache,mode=max
        file: python/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pthomison/tailscale-ingress-controller:${{env.tag}}